apply plugin: 'java-library'

dependencies {
    api ("io.springfox:springfox-swagger2:2.8.0") {
        exclude group: "org.springframework"
    }
    api ("io.springfox:springfox-swagger-ui:2.8.0"){
        exclude group: "org.springframework"
    }
    api "org.springframework.boot:spring-boot-starter-web:$springBootVersion"

}
