
// Temporarily commenting out docker-compose plugin to allow basic building
// buildscript {
//     repositories {
//         mavenCentral()
//     }
//     dependencies {
//         classpath "com.avast.gradle:gradle-docker-compose-plugin:0.14.13"
//     }
// }

// apply plugin: 'docker-compose'
apply plugin:'io.spring.dependency-management'

apply plugin: IntegrationTestsPlugin

// Temporarily commenting out docker-compose configuration
// dockerCompose {
//
//     startedServices = [ 'not-used']
//
//     integrationTests {
//         if (System.getenv("FTGO_DOCKER_COMPOSE_FILES") != null)
//             useComposeFiles = System.getenv("FTGO_DOCKER_COMPOSE_FILES").split(",").collect { "../" + it }
//
//         startedServices = [ 'mysql']
//         stopContainers = false
//     }
// }
//
// integrationTest.dependsOn(integrationTestsComposeUp)

dependencies {


    implementation project(":common-swagger")
    implementation project(":ftgo-domain")

    implementation project(":ftgo-consumer-service-api")
    implementation project(":ftgo-restaurant-service-api")
    implementation project(":ftgo-order-service-api")
    implementation project(":ftgo-consumer-service")

    implementation "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    implementation "io.micrometer:micrometer-registry-prometheus:$micrometerVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation 'javax.el:javax.el-api:2.2.5'

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"

    testImplementation "io.rest-assured:rest-assured:$restAssuredVersion"
    testImplementation "io.rest-assured:spring-mock-mvc:$restAssuredVersion"
    testImplementation "io.rest-assured:json-path:$restAssuredVersion"

    testImplementation project(":ftgo-test-util")
}
