apply plugin: FtgoServicePlugin

dependencies {
    implementation project(":ftgo-common")
    implementation project(":ftgo-domain")
    implementation project(":ftgo-consumer-service")
    implementation project(":ftgo-order-service")
    implementation project(":ftgo-restaurant-service")
    implementation project(":ftgo-courier-service")

    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"

    runtimeOnly 'mysql:mysql-connector-java:8.0.33'

    testImplementation project(":ftgo-end-to-end-tests-common")
}
