dependencies {
    implementation project(":common-swagger")
    implementation project(":ftgo-restaurant-service-api")
    implementation project(":ftgo-domain")

    implementation "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"

    implementation 'javax.el:javax.el-api:2.2.5'

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    testImplementation "io.rest-assured:rest-assured:$restAssuredVersion"
    testImplementation "com.jayway.jsonpath:json-path:2.3.0"
}
