apply plugin: 'java-library'

dependencies {
    api project(":ftgo-consumer-service-api")
    api project(":ftgo-restaurant-service-api")
    api project(":ftgo-order-service-api")
    api project(":ftgo-courier-service-api")

    api "junit:junit:4.12"
    api "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    api "io.rest-assured:rest-assured:$restAssuredVersion"
    api "com.jayway.jsonpath:json-path:2.3.0"
}
