dependencies {
    implementation project(":ftgo-courier-service-api")

    implementation project(":common-swagger")
    implementation project(":ftgo-domain")

    implementation "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    implementation "io.micrometer:micrometer-registry-prometheus:$micrometerVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation 'javax.el:javax.el-api:2.2.5'

    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"

    testImplementation "io.rest-assured:rest-assured:$restAssuredVersion"
    testImplementation "io.rest-assured:spring-mock-mvc:$restAssuredVersion"
    testImplementation "io.rest-assured:json-path:$restAssuredVersion"

    testImplementation project(":ftgo-test-util")

}
